name: tracking
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - natsort
  - click
  - napari-animation
  - scikit-image
  - python=3.12
  - nd2
  - jupyterlab
  - ffmpeg
  - numpy
  - dask
  - pandas
  - dask-image
  - imageio
  - pyqt
  - matplotlib
  - tqdm
  - napari
  - seaborn
